[package]
name = "webview"
version = "0.1.0"
authors = ["Rob Saunders <hello@robsaunders.io>"]

[lib]
name="webview"
crate-type = ["rlib"]

[dependencies]
objc = "0.2.2"
cocoa = "0.15.0"

[dev-dependencies]
winit = "0.13.1"
